//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C_Datos.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        public int IdSolicitud { get; set; }
        public int idusuario { get; set; }
        public int idvacante { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Vacantes Vacantes { get; set; }
    }
}
