//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C_Datos.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacantes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vacantes()
        {
            this.Solicitud = new HashSet<Solicitud>();
        }
    
        public int IdVacante { get; set; }
        public int idcategoria { get; set; }
        public string Empresa { get; set; }
        public string Posicion { get; set; }
        public string Descripcion { get; set; }
        public string Horario { get; set; }
        public string Ubicacion { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud> Solicitud { get; set; }
    }
}
